import Image from '@/components/common/image'
import SourceProvider from '@/libs/source'
import { UseTinaWithRouter } from '@/libs/tina'
import type { Metadata } from 'next'
import Link from 'next/link'
import bitesImage from '../../../public/BITES-150x150.png'
import eventsImage from '../../../public/EVENTS.png'
import exploreImage from '../../../public/explore-tag-3-150x150.png'
import logo from '../../../public/logo-768x721.png'
import qaImage from '../../../public/qa-tag-150x150.png'
import storyImage from '../../../public/story.png'
import travelImage from '../../../public/travel-tag-768x721.png'
import client from '../../../tina/__generated__/client'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const menuItems = [
  {
    title: 'Story',
    image: storyImage,
    href: '/story',
  },
  {
    title: 'Events',
    image: eventsImage,
    href: '/event',
  }, {
    title: 'Travel',
    image: travelImage,
    href: '/travel',
  },
  {
    title: 'Home',
    image: logo,
    href: '/',
  },
  {
    title: 'Bites',
    image: bitesImage,
    href: '/bites',
  },
  {
    title: 'Explore',
    image: exploreImage,
    href: '/explore',
  },
  {
    title: 'Q&A',
    image: qaImage,
    href: '/qa',
  },
]
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const props = await client.queries.page({ relativePath: 'all.md' })
  return (
    <SourceProvider defaultsource={props.data}>
      <UseTinaWithRouter />
      <html lang="en" data-theme="light">
        <body className={"bg-[#c2c5ff] min-h-screen"}>
          <header className='flex gap-6 justify-center px-6 lg:px-12 z-20 relative'>
            <ul className='justify-center  max-w-5xl w-full items-center gap-6 hidden lg:flex'>
              {
                menuItems.map((item, index) => {
                  return <li key={index} className='flex flex-1 flex-col  items-center gap-2 relative after:content-[""] after:pb-[100%]'>
                    <a href={item.href} className='hover:scale-110 duration-500 ease-in-out transition-transform absolute inset-0'>
                      <Image src={item.image} fill alt={item.title} className='object-cover' />
                      <div className='hidden'>{item.title}</div>
                    </a>
                  </li>
                })}
            </ul>
            <div className='flex gap-6 justify-between lg:hidden w-full z-20'>
              <Link href="/" className='w-[150px]'>
                <Image src={logo} alt='logo' className='object-cover' />
              </Link>
              <div className="flex items-center space-x-6"
              >
                <button className="flex flex-col lg:flex-row items-stretch uppercase  font-sweetsans  text-3xl text-white">
                  <svg fill="currentColor" width="1em" height="1em" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 116.93 111.19">
                    <g>
                      <path d="M51.4,68.9,38,97.81H33.47L20.06,68.9h5.66l10,22.58H36L46,68.9Z" />
                      <path d="M57.38,97.81V68.9h5V97.81Z" />
                      <path d="M88.41,84.93H77.3v8.45H96.87v4.43H72.34V68.9H95.8v4.43H77.3V80.5H88.41Z" />
                      <path d="M0,0V111.19H116.93V0ZM92.68,12a21.2,21.2,0,0,1,13.46,5.22l-3.45,3.1a15,15,0,0,0-10-3.9c-6.25,0-10.63,5-10.63,10.94,0,5.57,3.81,10.89,11.11,10.89,3,0,6.55-.89,8.5-2.35v-5.8H92.64V25.7h13.59V38.36A23.78,23.78,0,0,1,92.9,42.7c-9.16,0-16-6.86-16-15.36A15.42,15.42,0,0,1,92.68,12Zm-49.27.88h4.38L64.48,33h0v-20h5V41.82H65.1L48.41,21.76h0V41.82h-5Zm-31.61,0H35.26v4.43H16.76v7.17H27.87v4.43H16.76v8.45H36.32v4.43H11.8Zm100.1,93.34H5V59.17H111.9Z" />
                    </g>
                  </svg>
                </button>
                <div className="group leading-none ">
                  <label htmlFor="menu-toggle" className="text-3xl text-white z-20 block">
                    <svg fill="currentColor" width="1em" height="1em" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 116.92 111.19">
                      <path d="M0,0V111.19H116.92V0ZM98.94,84.48H18v-10h81Zm0-23.9H18v-10h81Zm0-23.91H18v-10h81Z" />
                    </svg>
                  </label>
                </div>
              </div>

            </div>
            <input type="checkbox" className="hidden peer" id="menu-toggle" />
            <ul className='justify-center animate-fade origin-top-right duration-300 text-center pt-[150px] p-12 flex-col   h-screen isolate fixed z-10 top-0 overflow-auto left-0 hidden bg-[#c2c5ff] peer-checked:flex  w-full items-center gap-6 '>
              {
                menuItems.map((item, index) => {
                  if (item.href === '/') {
                    return null
                  }
                  return <li key={index} style={{
                    animationDelay: `${(index + 1) * 100}ms`
                  }} className='flex w-full flex-1 flex-col animate-fade-up  items-center gap-2 relative max-w-xs'>
                    <Link href={item.href} className='hover:scale-110 flex items-center duration-500 ease-in-out transition-transform absolute inset-0  h-full'>
                      <div className='text-2xl font-semibold w-full uppercase'>{item.title}</div>
                    </Link>
                  </li>
                })}
            </ul>
          </header>
          <main className='px-6 lg:px-12 pb-12'>
            {children}
          </main>
        </body>
      </html>
    </SourceProvider>
  )
}
