import Image from '@/components/common/image'
import type { Metadata } from 'next'
import { Shantell_Sans } from 'next/font/google'
import bitesImage from './_assets/BITES-150x150.png'
import eventsImage from './_assets/EVENTS.png'
import exploreImage from './_assets/explore-tag-3-150x150.png'
import logo from './_assets/logo-768x721.png'
import qaImage from './_assets/qa-tag-150x150.png'
import storyImage from './_assets/story.png'
import travelImage from './_assets/travel-tag-768x721.png'
import './globals.css'
const sans = Shantell_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const menuItems = [
  {
    title: 'Story',
    image: storyImage,
    href: '/story',
  },
  {
    title: 'Events',
    image: eventsImage,
    href: '/event',
  }, {
    title: 'Travel',
    image: travelImage,
    href: '/travel',
  },
  {
    title: 'Home',
    image: logo,
    href: '/',
  },
  {
    title: 'Bites',
    image: bitesImage,
    href: '/bites',
  },
  {
    title: 'Explore',
    image: exploreImage,
    href: '/explore',
  },
  {
    title: 'Q&A',
    image: qaImage,
    href: '/qa',
  },
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sans.className + " " + "bg-[#c2c5ff]"}>
        <header className='flex gap-6 justify-center px-6 lg:px-12'>
          <ul className='flex justify-center  max-w-5xl w-full items-center gap-6'>
            {
              menuItems.map((item, index) => {
                return <li key={index} className='flex flex-1 flex-col  items-center gap-2 relative after:content-[""] after:pb-[100%]'>
                  <a href={item.href} className='hover:scale-110 transition-transform absolute inset-0'>
                    <Image src={item.image} fill alt={item.title} className='object-cover' />
                    <div className='hidden'>{item.title}</div>
                  </a>

                </li>
              })}
          </ul>
        </header>
        <main className='px-6 lg:px-12 pb-12'>
          {children}
        </main>
      </body>
    </html>

  )
}
